server:
  port: 8080

spring:
  application:
    name: gateway
  main:
    allow-bean-definition-overriding: true
    web-application-type: reactive
    banner-mode: off

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    by.ezer.gateway: INFO